<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\X.Shared\X.Shared.csproj" />
    <ProjectReference Include="..\X.Services.Order.Domain\X.Services.Order.Domain.csproj" />
    <ProjectReference Include="..\X.Services.Order.Infrastructure\X.Services.Order.Infrastructure.csproj" />
  </ItemGroup>

</Project>
